### ISSUE TITLE
some warning message about float index number 

### ISSUE THREAD

**Issue by xichaoqiang** [ManuelHobiger/RayDec#2]
Dear Dr.Hobiger,

A warning message will show in line33, because K is float number.
```
K=K0/nwind;
```
I think the flowing code is better.
```
K=floor( K0/nwind);
```

**Comment by ManuelHobiger** [comment]
You are right, this is a good idea. I never had that problem because I normally used signals with a "round" length that can be divided by the number of windows. I updated the code.
