### ISSUE TITLE
some nan will exist in low frequency band

### ISSUE THREAD

**Issue by xichaoqiang** [ManuelHobiger/RayDec#3]
Dear Dr Hobiger

I noticed that when the split time is relatively short, there will be nan values in the low frequency range. When the segment time is long, these nan values will disappear.
I usually collect traffic noise data for 30 minutes to 1 hour because the dispersion energy of multiple surface waves has stabilized. In this case, how to choose the segment duration? 

Best regards,
Xi

![image](https://user-images.githubusercontent.com/30900789/124580162-7382d180-de82-11eb-9adb-2538409518b0.png)

**Comment by ManuelHobiger** [comment]
Dear Xi,

It depends on the frequencies you want to resolve. The lower the frequencies, the longer the recording time has to be. But there is no clear rule. You should try out what gives you good results. Less time windows will give you a worse statistic on the uncertainty at higher frequency. Anyway, you can also combine the data from different parameterizations in the end.

Best regards,
Manuel

**Comment by xichaoqiang** [comment]
Dear Dr Manuel

Thanks for your reply.

I’ll try to use the longer  segment window to avoid the nan value.

I will also combine the data from different parameterizations as your suggestion.

Best regards,
Xi
